[theme]
base="light"
primaryColor="#D97757"
backgroundColor="#F0EEE6"
secondaryBackgroundColor="#E3DACC"
textColor="#3D3A2A"
linkColor = "#174C4F"
linkUnderline = false
codeBackgroundColor = "#ecebe4"
font="sans serif"
baseRadius = "3rem"
